#!/bin/bash
set -f
pub_command="gnome-terminal"
entity_id=0
for ip in {0..3..1}
do
	pub_command="$pub_command --tab -e \"bash -c \\\"./image_viewer -e ptgrey.$entity_id -f 5.0 -w 1288 -h 728 -t RGB -o $entity_id.mpeg; exec bash\\\"\""
	((entity_id++))
done

bash -c "$pub_command"