#!/bin/bash

__USER=$USER

# Get super user privileges
if [[ $EUID != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi

function pull {
	if cd $(basename $1); then 
		git pull 
		cd .. 
	else 
		git clone $1 
	fi
}

apt-get update
apt-get install -y build-essential cmake git pkg-config autoconf libtool # base
apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev # opencv
apt-get install -y libarmadillo-dev libopenblas-dev liblapack-dev liblapacke-dev # others 
apt-get install -y libvorbis-dev libudev-dev libjpeg-dev libopenal-dev # sfml 
apt-get install -y libavcodec-dev libavutil-dev # libav 

mkdir -p /tmp/is_install/ && cd /tmp/is_install/ 

pull https://github.com/alanxz/rabbitmq-c
pull https://github.com/alanxz/SimpleAmqpClient
pull https://github.com/msgpack/msgpack-c
pull https://github.com/gabime/spdlog
pull https://github.com/opencv/opencv
pull https://github.com/labviros/is-cpp

echo "
find_package(Boost 1.63.0 REQUIRED QUIET)

if(NOT Boost_FOUND)
  execute_process(COMMAND install_boost
                WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
endif() 

add_subdirectory("rabbitmq-c")
add_subdirectory("SimpleAmqpClient")
add_subdirectory("msgpack-c")
add_subdirectory("spdlog")
add_subdirectory("is-cpp")

" > CMakeLists.txt

mkdir -p build && cd build && cmake .. && make install